### ISSUE TITLE
Keep user logged in

### ISSUE THREAD

**Issue by yarnball** [christophior/ReactFirebaseAuth#1]
Hi,

Great repo- very straight forward.

However, when I refresh- it logs the user out.

Is there a way to set the user to stay logged in until they manually log out or set a time limit?

Thanks

**Comment by christophior** [comment]
Hey @yarnball,

Thanks for checking out the repo and finding it useful. I actually have also noticed this and was not sure if that was something that only happens when running locally or if this was an actual issue. I haven't actually tried getting this code and putting it in production to see if the issue persists there but when I have time i'll check it out.

Off the top of my head I don't know the solution to this but maybe someone like @kentcdodds would have some experience with this, i'm also going to tag @ryanflorence and see if he can help answer this.

**Comment by kentcdodds** [comment]
Without looking at the repo at all..... I'd keep the token in localStorage or sessionStorage (evaluate the tradeoffs) and load that up when the app starts. Then for the time limit thing, you should probably have a time to live on the token or just manually track how long the user's been logged in and clear their token after that time is up.

**Comment by christophior** [comment]
Updated the repo to firebase 3.4.X and solved this issue as well. Closing.

**Comment by yarnball** [comment]
Awesome work Christopher 👍 

The only issue now is, that when you refresh the page, it gives a "cannot get /dashboard" error (but the user still remains logged in).

**Comment by christophior** [comment]
The error you're getting is because I was using browserHistory, I moved this back to using hashHistory so now you can go to http://localhost:8000/#/dashboard multiple times and it'll work each time (but with a different hash each time)

**Comment by christophior** [comment]
This should help https://github.com/ReactTraining/react-router/blob/master/upgrade-guides/v2.0.0.md#using-history-with-router

**Comment by yarnball** [comment]
Cheers. Read through the docs and was a little confused. Basically when I refresh, it doesn't give the 404 "cannot get" but it does not direct to the right page on refresh. 
- I login, it goes to /dashboard
- I click refresh
- It goes back to the login page

Any ideas on that?
